[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"


[project]
# cf. tool.setuptools.package-dir section below
name = "good-devops-practice"
description = "Secure software development standards and practices"
version = "0.0.0"
# cf. https://www.bitecode.dev/p/relieving-your-python-packaging-pain,
# https://devguide.python.org/versions/
requires-python = ">=3.10"
# cf. https://pypi.org/classifiers/
classifiers = [
    "Private :: Do Not Upload",
    "Development Status :: 1 - Planning",
]
# To avoid unnecessary developer overhead, only set version
# constraints to address capability, compatibility, or security
# issues, and avoid pinning specific versions if possible.
dependencies = [
]


[project.optional-dependencies]
dev = [
    "autopep8",
    "black",
    "build",
    "flake8-bugbear",
    "flake8-pytest-style",
    "id",
    "isort",
    "jedi",
    "matplotlib",
    # https://github.com/executablebooks/mdit-py-plugins/pull/65
    "mdit-py-plugins>0.3.4",
    "myst-parser[linkify,rtd]",
    "pip-tools",
    "pre-commit",
    "psycopg2",
    "pystemmer",
    "python-semantic-release",
    "rinohtype",
    "sphinx-intl",
    "sphinx-multiversion @ git+https://github.com/Holzhaus/sphinx-multiversion#egg=sphinx-multiversion",
    "sphobjinv",
    "twine",
    "yapf",
    "yq",
]
test = [
]


[project.readme]
file = "README.md"
content-type = "text/markdown"


[tool.isort]
profile = "black"
skip_gitignore = true


[tool.pytest.ini_options]
# Recommended for new projects;
# cf. https://docs.pytest.org/en/latest/explanation/goodpractices.html#choosing-an-import-mode.
addopts = [
    "--import-mode=importlib",
]
# Invoke smoke tests with `pytest -k smoke` or `pytest -m "smoke and
# not slow"`.  See also https://docs.pytest.org/en/stable/mark.html,
# https://stackoverflow.com/a/52369721.
markers = [
    "slow",
    "smoke",
]


[tool.semantic_release]
commit_message = "release: cut the v{version} release\n\nAutomatically generated by python-semantic-release"
version_toml = [
    "pyproject.toml:project.version",
]


[tool.semantic_release.changelog.environment]
autoescape = true


[tool.semantic_release.commit_author]
env = "GIT_COMMIT_AUTHOR"
default = "semantic-release <semantic-release>"


[tool.setuptools.package-dir]
good_devops_practice = "src/good_devops_practice"
